config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :images
  get 'probar', to: 'control#saludo'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
    def index
        @images = Image.all
    end

    def create
        # render plain: params[:image].inspect
        @image = Image.new image_params
        @image.save
        redirect_to @image
    end
    
    def new
        @image = Image.new
    end

    def show
        @image = Image.find params[:id]
    end
    def edit
        @image = Image.find params[:id]
    end
    def update
        @image = Image.find params[:id]
        @image.update image_params
        redirect_to @image
    end
    private
    def image_params
        params.require(:image).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for @image do |f| %>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
    <br>
    <%= f.submit %>
<% end %>

app/views/images/_image.html.erb
<%= image.description %> <%= link_to 'Edit', edit_image_path(image) %><br>

app/views/images/edit.html.erb
<p>Editar imagen</p>
<%= render 'form' %>

app/views/images/index.html.erb
<!-- <ul>
    <%- @images.each do |image| %>
        <li><%= image.description %></li>
    <% end %>
</ul> -->
<!-- <ul>
    <li><%= render @images %></li>
</ul> -->
<%= render @images %>

app/views/images/new.html.erb
<p>Nueva Imagen</p>
<%= render 'form'%>

app/views/images/show.html.erb
<p><%= @image.description %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsgram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>